# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac279f7146cf29dab67a39eb5a6e9d78397aab9efbade8b2a79b089b0eda2b2e369736c7f1eb294af62e4eaf0ce00dcbd9dae4f8399a8e355404c20d63279d47

test:
  secret_key_base: 693674d0327b17eaeeabede005e6deb84121e639131aa04b13f7605310a16631a63f7ded788da7f9c325c77a7ad0b7c5e8d2a3eaa22ab2a5db5f112c8da7f836

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
