local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

google:
  service: GCS
  project: trans-app
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'] %>
  bucket: trans-app

google_dev:
  service: GCS
  project: trans-app
  credentials: <%= Rails.root.join("config/secrets/trans-app.json") %>
  bucket: trans-app
